# Generated by Django 5.2.10 on 2026-02-17 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoessay',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='log',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
