# Generated by Django 5.2.10 on 2026-05-07 09:28

import math
from django.db import migrations, models
import django.core.validators


def update_ratings(apps, schema_editor):
    Log = apps.get_model('movie_csv', 'Log')
    for log in Log.objects.all():
        # Convert from 0-10 scale to 0-5 scale by dividing by 2 and rounding
        log.rating = round(log.rating / 2.0)
        log.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0006_collection'),
    ]

    operations = [
        migrations.RunPython(update_ratings, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='log',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
