# Generated by Django 5.2.10 on 2026-05-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0007_alter_log_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
