# Generated by Django 5.2.10 on 2026-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0008_collection_is_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoessay',
            name='duration',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
