# Generated by Django 5.2.10 on 2026-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0009_videoessay_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
