# Generated by Django 5.2.10 on 2026-09-21 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0011_flag_watchlists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_watchlist', True)), fields=('owner',), name='one_watchlist_per_owner'),
        ),
    ]
