# Generated by Django 5.2.10 on 2026-09-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0012_one_watchlist_per_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-date', '-id')},
        ),
    ]
