# Generated by Django 5.2.10 on 2026-03-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_owner_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
