# Generated by Django 5.2.10 on 2026-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_drop_legacy_follow_m2ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
