# Generated by Django 5.2.10 on 2026-01-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoessay',
            name='highlighted',
        ),
    ]
