# Generated by Django 5.2.10 on 2026-01-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0002_remove_videoessay_highlighted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='owner',
        ),
    ]
