# Generated by Django 4.2.26 on 2025-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0002_log_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='creator_country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
