# Generated by Django 4.2.26 on 2025-12-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0003_rename_director_movie_creator_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='VideoEssay',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='movie',
            new_name='essayTitle',
        ),
    ]
