# Generated by Django 4.2.26 on 2026-01-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0004_rename_movie_videoessay_rename_movie_log_essaytitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='essayTitle',
            new_name='essay',
        ),
    ]
