# Generated by Django 4.2.26 on 2026-01-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0005_rename_essaytitle_log_essay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoessay',
            old_name='release_date',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='videoessay',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='videoessay',
            name='creator_country',
        ),
        migrations.AddField(
            model_name='videoessay',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoessay',
            name='channel_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoessay',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoessay',
            name='subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoessay',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoessay',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoessay',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videoessay',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
