# Generated by Django 4.2.26 on 2026-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0006_rename_release_date_videoessay_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoessay',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
