# Generated by Django 4.2.26 on 2026-01-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0007_videoessay_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoessay',
            name='published_date',
        ),
    ]
