# Generated by Django 4.2.26 on 2026-01-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0008_remove_videoessay_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoessay',
            name='youtube_id',
        ),
    ]
