# Generated by Django 4.2.26 on 2026-01-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_csv', '0009_remove_videoessay_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoessay',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
